language: php
php:
  - '7.1'
  - '7.2'

branches:
  only:
  - master

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

jobs:
  include:
    - stage: lint
      script: phpcs --standard=PSR2 src/
    - stage: test
      script: phpunit --configuration phpunit.xml